name: echemdb
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5,<6
  - black
  - filelock>=3,<4
  - frictionless>=5.10.1,<6
  - isort
  - jupytext>=1.13,<2
  - matplotlib-base>=3.5.0,<4
  - myst-nb>=0.17.0,<0.18
  - myst-parser>=0.18,<0.19
  - pandas>=1,<2
  - pip
  - plotly>=5,<6
  - pybtex>=0.24,<0.25
  - pylint
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - python>=3.9
  - sphinx>=4.3,<5
  - svgdigitizer>=0.9.1,<0.10.0
  - pip:
    - linkchecker
    - sphinx_rtd_theme>=1,<2
