name: unitpackage
channels:
  - conda-forge
  - defaults
dependencies:
  - jupytext>=1.13,<2
  - ipywidgets
  - notebook
  - pip
  - python>=3.9,<3.11
  - unitpackage==0.8.0
  - pip:
    - bash_kernel
